version: '3.8'

services:
  service-discovery:
    image: discovery-service:0.0.1-SNAPSHOT
    environment:
      SERVER_PORT: 8080
    ports:
      - 8761:8080

  service-exam:
    image: exam:0.0.1-SNAPSHOT
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://service-discovery:8080/eureka/
    ports:
      - 8081:8080
    depends_on:
      - service-discovery
      - service-math
      - service-history

  service-math:
    image: math:0.0.1-SNAPSHOT
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://service-discovery:8080/eureka/
    ports:
      - 8082:8080
    depends_on:
      - service-discovery

  service-history:
    image: history:0.0.1-SNAPSHOT
    environment:
      SERVER_PORT: 8080
      DISCOVERY_URL: http://service-discovery:8080/eureka/
    ports:
      - 8083:8080
    depends_on:
      - service-discovery